### ISSUE TITLE
GPU hashing

### ISSUE THREAD

**Issue by not-an-aardvark** [not-an-aardvark/lucky-commit#1]
lucky-commit has a bit of an annoying usability issue in that it takes an average of 20 minutes to generate a desired 7-character hash. This seems to be a limit of node's [crypto](https://nodejs.org/api/crypto.html) performance; computing 16<sup>7</sup> sha1 hashes in a loop seemed to yield similar performance.

I've been thinking about whether it would be possible to make lucky-commit work utilizing [hashcat](https://github.com/hashcat/hashcat) instead. Hashcat is basically an optimized hashing library written in C. Its main purpose is cracking passwords to match a hash, but what lucky-commit does is actually pretty similar, and lucky-commit's core functionality can almost be entirely replicated with hashcat. Based on benchmarks from my computer, hashcat can compute raw sha1 hashes over 8 times faster than node can (partially due to the fact that it can use multiple threads).

The issue with hashcat is that I can't find a way to check for a truncated hash match (i.e. hashing until the first _n_ characters match some target). I might try to add an extension to hashcat for that functionality.

**Comment by EtherDream** [comment]
Hashcat is designed to crack the password, not mining. You can implement your own mining algorithm, it is not difficult. Here is a live example: http://www.etherdream.com/FunnyScript/glminer/glminer.html

**Comment by not-an-aardvark** [comment]
Wow, that's pretty cool. Do you also have a GPU SHA1 implementation?

Also, how would I run something like that on Node? I've found [WebMonkeys](https://github.com/MaiaVictor/WebMonkeys) which seems to be related to what I want, but I'm not really sure what I'm doing since I don't know much about GPUs.

**Comment by EtherDream** [comment]
Hashcat has implemented a highly optimized SHA1 algorithm: https://github.com/hashcat/hashcat/blob/master/OpenCL/m00100_a0.cl (100 is sha1), maybe you can use opencl + nodejs c bindings
