### ISSUE TITLE
Add console output for successful execution

### ISSUE THREAD

**Issue by Marcono1234** [not-an-aardvark/lucky-commit#14]
Currently when lucky-commit succeeds there is no output in the console. This makes you wonder whether it succeeded (but on the other hand creates a surprise effect when you then run `git log`).

What do you think about printing a message to console on success? That message could for example contain the new commit hash.

**Comment by not-an-aardvark** [comment]
Thanks for the suggestion, but I think I prefer the silent behavior. If the tool fails for some reason, it should hopefully print an error message anyway, so ideally there won't be confusion about whether the tool succeeded.
