### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by 5alidshammout** [not-an-aardvark/lucky-commit#21]
can you make it a vscode extension

**Comment by not-an-aardvark** [comment]
I don't have any plans to turn this into a vscode extension, but you're certainly welcome to build a vscode extension yourself that uses this internally.

**Comment by kasthack** [comment]
@5alidshammout you can register a commit hook that would automatically apply `lucky_commit`.

**Comment by kasthack** [comment]
> the problem is that I don't know rust

Commit hooks a written in bash, though. My global `post-commit` is just two lines:

```bash
#!/bin/sh
lucky_commit 00000000
```

>and I use GitHub desktop

I use a third-party GUI as well, but all of these tools call plain git under the hood.
