### ISSUE TITLE
doing a specific hash is somehow MUCH slower than the default

### ISSUE THREAD

**Issue by JacksonChen666** [not-an-aardvark/lucky-commit#23]
i was playing around a bit with [hyperfine](https://github.com/sharkdp/hyperfine), stumbled upon an option called `--parameter-scan`, chose a random max number (7 digits) and a min number of `9371543` based on the max number with a bit of subtraction, and ran the thing

somehow, lucky_commit was doing a hash of `9371543` around 6 times slower than `0000000` (assumed to be the default of lucky_commit)

i decided to test if it was just weird thing. nope, it is consistently slower.

<details><summary>device details</summary>

- m1 mac (13 inch 2020, not pro or max or ultra)
- running macos 12.3 (21E230)
- architecture of program (or the `file` command): `/Users/jackson/.cargo/bin/lucky_commit: Mach-O 64-bit executable arm64`
- 8gb of memory

</details>

<details><summary>benchmark details</summary>

- gpu was used (99% usage basically)
- command: `hyperfine --warmup 10 --export-json ../benchmark.json --runs 25 "lucky_commit 9371543" "lucky_commit 0000000"`
- output (uncolored):
```
Benchmark 1: lucky_commit 9371543
  Time (mean ± σ):     917.1 ms ±   5.9 ms    [User: 61.1 ms, System: 83.7 ms]
  Range (min … max):   908.7 ms … 931.2 ms    25 runs
 
Benchmark 2: lucky_commit 0000000
  Time (mean ± σ):     155.9 ms ±   3.2 ms    [User: 27.2 ms, System: 23.4 ms]
  Range (min … max):   148.7 ms … 161.1 ms    25 runs
 
Summary
  'lucky_commit 0000000' ran
    5.88 ± 0.13 times faster than 'lucky_commit 9371543'
```
- git repo (last state i left it in): [repo.bundle.zip](https://github.com/not-an-aardvark/lucky-commit/files/8352208/repo.bundle.zip)
  - commits were not signed
  - 1 commit
  - [how to "use"](https://stackoverflow.com/questions/39940351/export-github-repository#39940468)
- raw benchmark data (json): [benchmark.json.zip](https://github.com/not-an-aardvark/lucky-commit/files/8352233/benchmark.json.zip)
- git repo location: the desktop
  - trying to run `lucky_commit` in `/tmp` on macos is actually somehow slower, so avoid that

</details>

**Comment by not-an-aardvark** [comment]
I haven't looked at the git repo yet (although thanks for posting it, I'll look into it more deeply when I'm not on mobile) -- but does this discrepancy still happen if you try to run `lucky_commit` on a different starting commit? For any given starting commit and desired prefix, the amount of hashes `lucky_commit` needs to compute is mostly deterministic. It could be that for your specific starting commit, a prefix of `0000000` "appears" sooner than a prefix of `9371543`, whereas this wouldn't be the case for a different starting commit.

By "mostly deterministic" I mean that `lucky_commit` will always start the same threads/GPU workloads. There could be rare cases where the final result varies based on how the threads interleave, if there are multiple threads that would both happen to find a matching commit at about the same time. But that rare case probably wouldn't be relevant to this benchmark.

Also, each run of `lucky_commit` omits any whitespace that was added by previous runs of `lucky_commit`, to prevent whitespace from accumulating forever. So if you run `lucky_commit` on a commit, then run it again on the modified commit without making any other changes to the commit, then you will effectively be picking the same random point on a distribution with each run, and the runs won't be independent from each other.

**Comment by JacksonChen666** [comment]
> I haven't looked at the test git repo yet (although thanks for posting it, I'll look into it more deeply when I'm not on mobile) -- but does this discrepancy still happen if you try to run `lucky_commit` on a different starting commit?

so i created another test repo with 1000 commits (either add or remove the empty `asdf` file from the repo), started a git rebase that `break`s every commit then ran `hyperfine --warmup 10 --export-json ../benchmark4.json --runs 25 -p "git rebase --continue" "lucky_commit 9371543" "lucky_commit 0000000"`. the result i got is the following:

```
Benchmark 1: lucky_commit 9371543
  Time (mean ± σ):     408.7 ms ± 341.7 ms    [User: 32.7 ms, System: 38.0 ms]
  Range (min … max):    77.6 ms … 1114.7 ms    25 runs
 
Benchmark 2: lucky_commit 0000000
  Time (mean ± σ):     423.3 ms ± 268.3 ms    [User: 32.7 ms, System: 37.8 ms]
  Range (min … max):    82.6 ms … 992.8 ms    25 runs
 
Summary
  'lucky_commit 9371543' ran
    1.04 ± 1.09 times faster than 'lucky_commit 0000000'
```

i should note that the program `hyperfine` can detect "statistical outliers", but it wasn't reported to contain such for the tests above.

> Also, each run of `lucky_commit` omits any whitespace that was added by previous runs of `lucky_commit`, to prevent whitespace from accumulating forever. So if you run `lucky_commit` on a commit, then run it again on the modified commit without making any other changes to the commit, then you will effectively be picking the same random point on a distribution with each run, and the runs won't be independent from each other.

so if i understand you correctly, what i was doing was *roughly* equivalent to the following:

[![xkcd 221, random number](https://imgs.xkcd.com/comics/random_number.png)](https://xkcd.com/221/)
<sup>["Random Number"](https://xkcd.com/221/) by ["xkcd"](https://xkcd.com/) licensed under [CC BY-NC 2.5](https://creativecommons.org/licenses/by-nc/2.5/)</sup>

and also that `lucky_commit` throws any previous work done by itself before it ran to avoid accumulate too much whitespaces.

**Comment by not-an-aardvark** [comment]
Thanks for doing the additional benchmarking. 

> so if i understand you correctly, what i was doing was roughly equivalent to the following:
>
> --snip--
>

Something like that, yes.

> and also that lucky_commit throws any previous work done by itself before it ran to avoid accumulate too much whitespaces.

Sort of, yes -- although I would say that it's only really "throwing away work" if someone searches for the same commit prefix on the same commit multiple times (otherwise, the whitespace from the previous commit message wouldn't be useful anyway).

**Comment by JacksonChen666** [comment]
i think i'll take this as "my issue, my bad"

unless you think it's somehow not (and that this is really is an issue), you may reopen the issue.
