### ISSUE TITLE
Is it possible to add random strings instead of blank strings to generate a nice looking hash?

### ISSUE THREAD

**Issue by winktool** [not-an-aardvark/lucky-commit#32]
Is it possible to add random strings instead of blank strings to generate a nice looking hash?

**Comment by winktool** [comment]
It's best to add random strings in any position.

**Comment by not-an-aardvark** [comment]
I don't understand the question. Could you clarify? What strings are you referring to?

**Comment by not-an-aardvark** [comment]
Closing, but feel free to open a new issue if you still have questions
