### ISSUE TITLE
Failed to create git object file: Not a directory

### ISSUE THREAD

**Issue by LoganDark** [not-an-aardvark/lucky-commit#4]
```
LoganDark@base ~/n/backend> lucky_commit
thread 'main' panicked at 'Failed to create git object file: Error { repr: Os { code: 20, message: "Not a directory" } }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm running it again right now, I'm going to post the backtrace here when it's done.

**Comment by LoganDark** [comment]
```
thread 'main' panicked at 'Failed to create git object file: Error { repr: Os { code: 20, message: "Not a directory" } }', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: lucky_commit::run_lucky_commit
  10: lucky_commit::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start
```

**Comment by LoganDark** [comment]
Okay, I found the issue. `.git` is a file due to this being a submodule. It contains:

```
gitdir: ../.git/modules/backend
```

**Comment by LoganDark** [comment]
This is trivial to fix, if `.git` begins with `gitdir:`, then take everything from index `9` onwards (zero-indexed) and use that instead of `.git` for the directory.

I'd open a PR, but I don't know Rust.

**Comment by LoganDark** [comment]
[Offender](https://github.com/not-an-aardvark/lucky-commit/blob/0000000ba7/src/main.rs#L310)

**Comment by LoganDark** [comment]
Scratch what I said about not knowing Rust. It turns out it's extremely easy to pick up, and I'm testing changes right now.

**Comment by LoganDark** [comment]
Okay, my solution works...

but Git is not accepting the new option.

`fatal: Could not parse object '0000000bcd7e5bfc8deae8487b3b2f7bc53738ca'.`

**Comment by not-an-aardvark** [comment]
That's odd -- could it be that the generated hash is incorrect? I think git does a sha1 checksum verification when it loads commits from the filesystem.

**Comment by LoganDark** [comment]
Maybe, but at least I know my fix works, even though an issue pops up (a completely different one, though). I'll open a pull request.
